import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const isWatch = process.argv.includes('--watch');

function syncStyles() {
  const cssPath = path.resolve('src/style.css');
  const tsPath = path.resolve('src/stylesString.ts');
  if (fs.existsSync(cssPath)) {
    const baseCss = fs.readFileSync(cssPath, 'utf-8');
    const katexCssPath = path.resolve('node_modules/katex/dist/katex.min.css');
    const katexCss = fs.existsSync(katexCssPath)
      ? fs.readFileSync(katexCssPath, 'utf-8').replace(/url\((['"]?)fonts\//g, 'url($1__GEMINI_ROOT__fonts/')
      : '';
    const cssContent = `${baseCss}\n\n/* KaTeX layout and font metrics; the root URI is filled in at Zotero startup. */\n${katexCss}`;
    const tsCode = `export const PLUGIN_CSS = ${JSON.stringify(cssContent)};\n`;
    fs.writeFileSync(tsPath, tsCode, 'utf-8');
  }

  // KaTeX relies on its TeX fonts for fraction, radical and delimiter metrics.
  // Keep them inside the XPI so the injected style sheet does not depend on a CDN.
  const fontsSource = path.resolve('node_modules/katex/dist/fonts');
  const fontsTarget = path.resolve('fonts');
  if (fs.existsSync(fontsSource)) {
    fs.cpSync(fontsSource, fontsTarget, { recursive: true });
  }
}

function syncPreferenceDefaults() {
  const defaultsPath = path.resolve('src/defaults.json');
  const outputPath = path.resolve('preferences-defaults.js');
  const defaults = JSON.parse(fs.readFileSync(defaultsPath, 'utf-8'));
  const source = `// Generated from src/defaults.json. Do not edit this file directly.\nglobalThis.GeminiTranslatorDefaults = Object.freeze(${JSON.stringify(defaults)});\n`;
  fs.writeFileSync(outputPath, source, 'utf-8');
}

syncStyles();
syncPreferenceDefaults();

const buildOptions = {
  entryPoints: ['src/bootstrap.ts'],
  bundle: true,
  outfile: 'bootstrap.js',
  target: 'firefox115',
  format: 'iife',
  footer: {
    js: 'var install = globalThis.install; var uninstall = globalThis.uninstall; var startup = globalThis.startup; var shutdown = globalThis.shutdown;',
  },
  logLevel: 'info',
};

try {
  if (isWatch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('Watching for changes in src/...');
  } else {
    await esbuild.build(buildOptions);
    console.log('Build successful: bootstrap.js generated');
  }
} catch (err) {
  console.error('Build failed:', err);
  process.exit(1);
}
